create table if not exists public.store_settings (
  id bigint primary key check (id = 1),
  phone text not null default '9846010948',
  whatsapp text not null default '9846010948',
  address text not null default 'MadhyaNepal-6, Bhorletar Lamjung',
  hours text not null default '6:00 AM - 8:00 PM',
  map_url text not null,
  updated_at timestamptz not null default now()
);

alter table public.store_settings add column if not exists phone text not null default '9846010948';
alter table public.store_settings add column if not exists whatsapp text not null default '9846010948';
alter table public.store_settings add column if not exists address text not null default 'MadhyaNepal-6, Bhorletar Lamjung';
alter table public.store_settings add column if not exists hours text not null default '6:00 AM - 8:00 PM';
alter table public.store_settings add column if not exists tagline text not null default 'गुणस्तरीय सामान आफ्नै घरछेउमा';

create table if not exists public.products (
  id bigint primary key generated by default as identity,
  name text not null,
  category text not null,
  unit text not null,
  price numeric not null check (price >= 0),
  available boolean not null default true,
  image_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists image_url text not null default '';
alter table public.products add column if not exists sort_order integer not null default 1;
alter table public.products add column if not exists stock_status text not null default 'in-stock' check (stock_status in ('in-stock', 'low-stock', 'out-of-stock'));

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

create policy "Public can read product images"
  on storage.objects for select
  using (bucket_id = 'product-images');

create policy "Public prototype can upload product images"
  on storage.objects for insert
  with check (bucket_id = 'product-images');

alter table public.store_settings enable row level security;
alter table public.products enable row level security;

create policy "Public can read store settings"
  on public.store_settings for select
  using (true);

create policy "Public prototype can update store settings"
  on public.store_settings for insert
  with check (true);

create policy "Public prototype can edit store settings"
  on public.store_settings for update
  using (true)
  with check (true);

create policy "Public can read products"
  on public.products for select
  using (true);

create policy "Public prototype can add products"
  on public.products for insert
  with check (true);

create policy "Public prototype can edit products"
  on public.products for update
  using (true)
  with check (true);

create policy "Public prototype can delete products"
  on public.products for delete
  using (true);

insert into public.store_settings (id, phone, whatsapp, address, hours, map_url)
values (1, '9846010948', '9846010948', 'MadhyaNepal-6, Bhorletar Lamjung', '6:00 AM - 8:00 PM', 'https://www.google.com/maps/place/Regmi+Grocery+Store+(%E0%A4%B0%E0%A5%87%E0%A4%97%E0%A5%8D%E0%A4%AE%E0%A5%80+%E0%A4%95%E0%A4%BF%E0%A4%B0%E0%A4%BE%E0%A4%A8%E0%A4%BE+%E0%A4%AA%E0%A4%B8%E0%A4%B2)/@28.154956,84.2401666,46m/data=!3m1!1e3!4m14!1m7!3m6!1s0x3995a0389d25966d:0x416c1ff848858d04!2sShree+Ishaneshwor+Higher+Secondary+School!8m2!3d28.1554512!4d84.2417554!16s%2Fg%2F11g8_8558p!3m5!1s0x3995a100579ad80d:0xf4a6759123baae72!8m2!3d28.1549179!4d84.2401895!16s%2Fg%2F11ygl1fpyb?entry=ttu&g_ep=EgoyMDI2MDkzMC4wIKXMDSoASAFQAw%3D%3D')
on conflict (id) do nothing;