export const storeCopy = {
  home: "Home",
  categories: "Categories",
  contact: "Contact",
  direction: "Direction",
  admin: "Admin",
  call: "Call the store",
  whatsapp: "WhatsApp",
  open: "Open today",
  heroEyebrow: "YOUR NEIGHBORHOOD GROCERY STORE",
  heroTitle: "Good staples, close to home.",
  heroIntro: "Browse everyday essentials, check the price, then call or WhatsApp us to order.",
  browse: "Start shopping",
  contactUs: "Contact us",
  shelf: "THE DAILY SHELF",
  shop: "Shop the essentials",
  categoriesEyebrow: "CATEGORIES",
  categoriesTitle: "Browse by category",
  searchProducts: "Search for products",
  searchCategories: "Search for categories",
  contactEyebrow: "CONTACT THE STORE",
  contactTitle: "Ready to ask about an item?",
  contactIntro: "Call or send a WhatsApp message and our team will help you check the shelf.",
  directionEyebrow: "GET DIRECTION",
  directionTitle: "Find us in Bhorletar.",
  directions: "Get directions",
};