"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { getCategories, getProducts, saveProduct, uploadProductImage, type Category, type Product, type StockStatus } from "../../../../lib/store-data";
import { sitePath } from "../../../../lib/site-path";
import "../../../admin/admin.css";
import "../../../admin/product-photo.css";

export default function EditProductForm({ productId, productIdFromParams }: { productId?: string; productIdFromParams?: Promise<{ id: string }> }) {
  const [product, setProduct] = useState<Product | null>(null);
  const [categories, setCategories] = useState<Category[]>([]);
  const [form, setForm] = useState({ name: "", category: "", unit: "", price: "", sortOrder: "", imageUrl: "", stockStatus: "in-stock" as StockStatus });
  const [busy, setBusy] = useState(false);
  useEffect(() => { (productIdFromParams ? productIdFromParams.then(({ id }) => id) : Promise.resolve(productId || "")).then((resolvedId) => Promise.all([getProducts(), getCategories()]).then(([products, nextCategories]) => { const current = products.find((item) => item.id === Number(resolvedId)); if (current) { setProduct(current); setForm({ name: current.name, category: current.category, unit: current.unit, price: String(current.price), sortOrder: String(current.sortOrder ?? 1), imageUrl: current.imageUrl || "", stockStatus: current.stockStatus ?? (current.available ? "in-stock" : "out-of-stock") }); } setCategories(nextCategories); })); }, [productId, productIdFromParams]);
  async function selectImage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusy(true); try { const imageUrl = await uploadProductImage(file); setForm((current) => ({ ...current, imageUrl })); } finally { setBusy(false); } }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!product) return; await saveProduct({ id: product.id, name: form.name.trim(), category: form.category, unit: form.unit.trim(), price: Number(form.price), sortOrder: Number(form.sortOrder) || 1, available: form.stockStatus !== "out-of-stock", stockStatus: form.stockStatus, imageUrl: form.imageUrl }); window.location.href = sitePath("/admin/products"); }
  if (!product) return <main className="admin-page"><p className="admin-empty">Product not found.</p></main>;
  return <main className="admin-page"><header className="admin-topbar"><a className="brand" href={sitePath("/admin/products")}><strong>Regmi Kirana Store</strong><small>Edit product</small></a><a className="admin-link" href={sitePath("/admin/products")}>Back to products</a></header><section className="admin-subpage admin-edit-page"><p className="eyebrow">EDIT PRODUCT</p><h1>{product.name}</h1><form className="add-form" onSubmit={submit}><div className="product-photo-editor">{form.imageUrl ? <img src={form.imageUrl} alt="Product preview" /> : <span>No photo selected</span>}<label className="photo-picker">{busy ? "Uploading..." : "Choose photo"}<input type="file" accept="image/*" onChange={selectImage} disabled={busy} /></label></div><div className="form-grid"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Product name" aria-label="Product name" /><select required value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} aria-label="Category">{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select><input required value={form.unit} onChange={(event) => setForm({ ...form, unit: event.target.value })} placeholder="Unit, e.g. 1 kg" aria-label="Unit" /><input required type="number" min="0" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} placeholder="Price in NPR" aria-label="Price in NPR" /><input required type="number" min="1" value={form.sortOrder} onChange={(event) => setForm({ ...form, sortOrder: event.target.value })} placeholder="Display position" aria-label="Display position" /></div><label className="availability-field"><span>Availability</span><select value={form.stockStatus} onChange={(event) => setForm({ ...form, stockStatus: event.target.value as StockStatus })} aria-label="Availability"><option value="in-stock">In Stock</option><option value="low-stock">Low Stock</option><option value="out-of-stock">Out of Stock</option></select></label><button className="button button-primary" type="submit" disabled={busy}>Save changes</button></form></section></main>;
}
